# Generated by Django 4.1 on 2023-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rim',
            name='pattern',
        ),
        migrations.AddField(
            model_name='tube',
            name='layer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
