# Generated by Django 4.1 on 2023-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_cartcontainsproduct_type_alter_cart_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='adress',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
